apiVersion: v1
kind: Service
metadata:
  name: worker-app
  labels:
    name: worker-app-service
    app: demo-voting-app
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    name: worker-app-pod
    app: demo-voting-app